[package]
name = "minesweeper_os"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["kernel"]


[build-dependencies]
bootloader = "0.11.5"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none"}
